### ISSUE TITLE
Diagrams: CU

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#106]
Add functionality and think about the application use.

**Comment by phf1001** [comment]
![cu_krini_v-1 drawio](https://user-images.githubusercontent.com/99904180/223715576-bd04aa37-c665-4411-949f-f531f5f0c6cc.png)

Hello! I have updated the [CU diagram](https://app.diagrams.net/#G1x9l1mXxviLkbtZERxMghQx89300HCjY3). What do you think? I have more functionality ideas, but I think is better to start with the "basics" (even though I don't find them to be basic 😥).

I don't know what to do with the "retrain" feature. Maybe it's better to just allow to add and delete models. Any thoughts on this?

Kind regards,

**Comment by alvarag** [comment]
It looks nice, but I need more information to understand everything. On the next meeting we will discuss it properly.
