### ISSUE TITLE
Mockups: general and already done screens

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#107]

**Comment by phf1001** [comment]
@alvarag Hello!

You can find attached some other mockups (and others that were missing).

Nice sunday!

[mockups_krini_v-2.pdf.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/10951597/mockups_krini_v-2.pdf.pdf)

**Comment by alvarag** [comment]
They look great, one comment:
- If the application is going to run more than one classifier, maybe instead of a barchart with yes/no, would be more interesting to have multiple bars (one for each classifier) or even a scatterplot...

Anyway, as mockup is perfect,it is not necessary to change it

**Comment by phf1001** [comment]
@alvarag okay! I wasn't completely sure about that part because of the selector in the main menu, but it can be a multiselector!

Thanks for the feedback!
