### ISSUE TITLE
Diagrams: class (web)

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#113]

**Comment by phf1001** [comment]
![web_class_diagram drawio(1)](https://user-images.githubusercontent.com/99904180/224502709-f5490afd-c47a-48a8-8d2b-92f9323cacf7.png)


Hello @alvarag !

Since the web development is doing well, I have decided to make a "serious" class model (because I want to start adding some functionality and it's going to be awful to change everything later). [Draw.io](https://app.diagrams.net/#G1PrrOhgITnzxiPkNc551E4CKW16JnHAOS).

This is the DB (posgresql) model. It is not intended to be a general class diagram, but a DB model to store what is available and what is not.

I would be grateful to hear your thoughts about it.

Nice weekend!

P.D. I have checked your diagrams tool but I am comfortable with Draw.io, hope you don't mind.

**Comment by alvarag** [comment]
Sorry, I have just realised that I did not answered to this issue.

I am not sure what kind of diagram is... we have different notations: databases and also UML? Maybe I am not understanding properly the whole diagram, we can check it in the next meeting
