### ISSUE TITLE
diagrams

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#120]
- [x] Modify CU and include new usecase (7.4 test models)
- [x] Delete 2.1 include
- [x] E/R diagram
- [x] User reporting relation atribute
- [x] Relational diagram
- [x] Data dictionary

**Comment by phf1001** [comment]
![1  er_krini_v-1](https://user-images.githubusercontent.com/99904180/225583570-7f98247d-1f33-453e-bb0c-45a3f251538c.png)

@alvarag Hi! can you please have a look at [this ER diagram](https://app.diagrams.net/#G1DrDN_NfjR4rdHKaqiqqYMLsA9R_z60yC)?

Few thoughts:

- There is a loop, but I believe it should be OK since (in my opinion) it is not redundant ([bib: page 11](http://ooatool.com/docs/OOA96.pdf)). What do you think?
- That loop can be removed by including a csv, but I think the fastest and easiest implementation is to keep the N:N purple relation. But that table relation may go wild (many, many rows). Thoughts?

As always, thanks for your feedback. Is really appreciated :)

**Comment by alvarag** [comment]
It looks nice but there are some changes that in my opinion should be considered:
- Unification of language: everything in English or Spanish, not mixed.
- Are we interested in knowing the user that suggested the instance to be accepeted? I men, in the diagram currently admin approves an instance but it looks that he/she is not interested in who reported it. If this is the case, no change is needed.
- I imagine that "file" attribute of entity Model is a binary file, i.e. the pickled algorithm, isn't it?
- "training_with" relation would be potentially huge, but in the diagram we can keep it and maybe in the future we will use a csv or other structure, but in the design phase is important to maintain it.
- A model can be related with models: tri-training has three, co-forest has n... Nevertheless I do not know whether or nor we want to retain that information here

**Comment by phf1001** [comment]
![krini-relational drawio](https://user-images.githubusercontent.com/99904180/225604262-7d6643a2-d9b0-4fca-8370-7c5f3f0917f6.png)

@alvarag attaching the [relational model](https://app.diagrams.net/#G1l15Uln5LpG0Evtp9wdrvbK83bORSwklY)! (notes will be deleted, that's why they are written in spanish)

**Comment by alvarag** [comment]
All right, I think it's a good starting point. Nevertheless Jesús Maudes is the master of the databases so if you want to ensure that it is correct: go to his room and check it with him. Maybe there are some changes that can be done to improve it

**Comment by phf1001** [comment]
@alvarag OK! I will try to reach him once the data dictionary is done. Thanks!
