### ISSUE TITLE
docs: Diagrams

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#135]
- [x] Sequence for index and (maybe) report URL
- [x] Classes

**Comment by phf1001** [comment]
@alvarag 

Good morning!

Can you please have a look at this [diagram](https://app.diagrams.net/#G1pYMAAiQcNjxuxRfy8wKeYYOAywJIJxRQ)? I've tried to "keep it simple", but the "flask" structure is driving me a bit crazy (like, I don't think templates are objects, but they definitely have an associated "method", so I have used them as if they were since maybe is easier to understand).

![index-v1](https://user-images.githubusercontent.com/99904180/229771631-0fda0cca-0192-4fd7-81e9-db07a8b63939.png)

Also, maybe some features are "new" to you. There is a difference between quick analysis (information is restored from the DB if it exists) and the analysis and it is that quick analysis don't return extra information to "decorate" the dashboard (since keeping that in the database is unnecessary).

Ex of quick analysis dahsboard:

![image](https://user-images.githubusercontent.com/99904180/229773241-03c992e5-5abc-4fc4-a6a4-f7baca1f76cb.png)

Ex of analyzed webpage dashboard (extra fv card):

![image](https://user-images.githubusercontent.com/99904180/229773541-9ba500d5-3a45-412c-8e1c-f1ccbc8694e5.png)

The quick analysis can be activated in the index:

![image](https://user-images.githubusercontent.com/99904180/229774522-6390770b-1f67-4912-b935-a7cc69c612d2.png)

Thanks for your help!

**Comment by alvarag** [comment]
I don't know what is the purpose of the nested alt: storing the instance in previous_instance?

The rest of the diagram I think can be followed... more or less.  One thing that I do not know whether or not could be helpful for simplifying the diagram is to divide it into quick analysis and the other one. But it's just an idea.

**Comment by phf1001** [comment]
The idea of the nested alt is to restore the white-list/black-list from the database if it exists (if there is no previous instance, it won't be restored).

Regarding the quick-analysis, I just programmed the function because I thought it was "natural", but I may have created  another use case unintentionally (?), (sorry 😖).

I am going to document the use case in a table and maybe after that we can decide if it has to be splitted.

**Comment by phf1001** [comment]
@alvarag 

Hi!

I am attaching the diagram to the[ report url ](https://app.diagrams.net/#G1jO0F48YtvaZ1ltm8g4jcyPV6N0H-21Gx)use case. I have tried to keep it simple and reduce "the number of objects" (it is a bit more abstract). 

![report_url drawio](https://user-images.githubusercontent.com/99904180/230044733-6988d488-aec6-4c22-90ac-74b5c6bd812f.png)

Thank you.

P.D. I have made some CU tables and are available in the [annexes](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/blob/dev/docs/anexos.pdf) (dev-branch). Those are focused on the user interaction with the application, and they are more abstract. What do you think?

Thank you so much!

**Comment by alvarag** [comment]
It's much easier to understand.

Some comments on the appendices

[anexosAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11157627/anexosAAG.pdf)
