### ISSUE TITLE
review: diagrams

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#183]
@alvarag 

Hello!

I am creating this "timeless issue" in order to discuss the new diagrams created without affecting the burn down report.

**Comment by phf1001** [comment]
# SEQUENCE DIAGRAMS

We already had the report_url and the index ones. I have created three more (just to have one per section). They are not 100% equal to the implementation so that they can be "smaller" and "easier" to understand. The "idea" of the sequence is the same. Once you have checked them and I have made all the corrections required, I will widely explain them in the annexes.

[sequence-accept_review.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11359566/sequence-accept_review.pdf)
[sequence-new_instance.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11359567/sequence-new_instance.pdf)
[sequence-test_model.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11359568/sequence-test_model.pdf)

**Comment by phf1001** [comment]
# DEPLOY DIAGRAM

I personally find this one so cute and "unproblematic"... Hope you do it too!

[deploy.drawio.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11359635/deploy.drawio.pdf)

P.D. I will update the "toc" diagram once the web is completed (just in case it needs any change...)

**Comment by alvarag** [comment]
About sequence diagrams: 
- why are some objects in bold and underlined while others not? For example New_instance and Instance.
- Report and available tags appear with boxes but without any message...

The deploy diagram is OK, no problem with it

**Comment by phf1001** [comment]
@alvarag Regarding your questions:

- The "objects" are in bold and underlined. The ones that aren't it's because they are "Flask screens" (they have a method, but aren't exactly an object...) Maybe is better if I change those screens with the "Form object", or something like that?
- The boxes without messages is because some attributes of those classes are being used by other calls (so, they are being used after all... even if not explicitly) Maybe is better to delete those ones?

Thanks

**Comment by alvarag** [comment]
We can check them carefully in the next meeting, there are minor issues but must be addressed.

**Comment by phf1001** [comment]
# CLASS DIAGRAMS

Leaving few here. I have done the "packages one" so that I can explain the "general view". Then I have done a "general" class diagram of the main functionality of the app and few little ones with some methods (not all of them). Also, I have tried to include a few of the sklearn inheritance (the fit and predict methods are overwritten).

[class-phishing_fvg.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11371591/class-phishing_fvg.pdf)
[packages.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11371592/packages.pdf)
[class-classifiers.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11371593/class-classifiers.pdf)
[class-general.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11371590/class-general.pdf)

**Comment by phf1001** [comment]
# TEST CASES

@alvarag Hello! could you please have a look at these so that I can include them on the annexes? Thank you!

[TFG-CasosPrueba-bueno.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11399459/TFG-CasosPrueba-bueno.pdf)

**Comment by alvarag** [comment]
Test cases are OK, only some minor issues:
- The symbols << and >> are a bit ugly as you can have them now. Maybe you can add these symbols (as symbols) in Word.
- In some test cases the input route (e.g. /index) are in bold and not in others.
- In CP-12 there is a lot of vertical space between actions 2 and 3.

Moreover, for a best integration in LaTeX, you can keep only one table for each page, later you can use pdfcrop for removing margins with the aim of giving the reader the feeling that the tables are actually in LaTeX
