### ISSUE TITLE
docs: phishing ssl vs sl + dataset extraction

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#191]

**Comment by alvarag** [comment]
Some comments on the documentation:

[anexosAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11428447/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11428448/memoriaAAG.pdf)


Good job.

**Comment by phf1001** [comment]
@alvarag Thanks! All corrections have been checked, will be including them (some sections like objectives/tools) according to the planning.
