### ISSUE TITLE
docs: corrections and relaunch graphs

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#209]

**Comment by alvarag** [comment]
Sorry, I started to check an old version of the annexes. I am attaching it now for not moving the comments to the new one. So, let's check these issues and then I'm starting with the updated version of the annexes, sorry.

[anexosAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11515924/anexosAAG.pdf)

**Comment by phf1001** [comment]
@alvarag Absolutely no problem! It was my bad, I forgot to push.

I will correct those during the weekend and we will see the rest during the next week.

Have a nice weekend 🌞

**Comment by alvarag** [comment]
I'm attaching the comments on annexes.
[anexos-AAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/11516175/anexos-AAG.pdf)

Have a nice weekend you too.
