### ISSUE TITLE
docs: annexes, repository config and corrections

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#92]

**Comment by alvarag** [comment]
Some annotations on the documents:

[memoriaAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/10822530/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/10822531/anexosAAG.pdf)

**Comment by alvarag** [comment]
If you want that I check a new version of the documentation let me know

**Comment by phf1001** [comment]
@alvarag Not yet! Fixing the webpage has taken much longer than expected and I have to update the docs (I will do it tomorrow and let you know when it's ready). I am also working on the Heroku deployment. Thanks!! (or... I would rather say Dziękuję ;) ?)

**Comment by alvarag** [comment]
Don't worry, I only wrote to you for informing you that I am available to check when you need it.

My Polish is still pretty bad :S

**Comment by phf1001** [comment]
Done! I've just added a few information to the docs (since Flask and Heroku is taking longer than expected...), but it can be checked.

The web has been moved to this repo, but was originally developed [here](https://github.com/phf1001/krini-frontend/tree/dev) (just in case you miss some commits).

Also, you can check the [Heroku site](https://krini.herokuapp.com/login), but the nav bar is not working :(. Few endpoints are /index, /report_url, /login, /register, /dashboard just in case you want to have a look!

Have a nice Sunday!
